# Generated by Django 6.0.2 on 2026-02-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_last_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='capital',
            field=models.CharField(blank=True, max_length=100, verbose_name='Capital'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='short_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dirección corta'),
        ),
    ]
