# Generated by Django 6.0.2 on 2026-02-08 04:22

import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_ordermessage_read_by_admin_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('binance', 'Binance'), ('paypal', 'PayPal'), ('zinli', 'Zinli'), ('banesco', 'Banesco'), ('pago_movil', 'Pago Móvil'), ('transfer', 'Transferencia Bancaria'), ('crypto', 'Criptomoneda'), ('card', 'Tarjeta'), ('other', 'Otro')], default='transfer', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordermessage',
            name='message',
            field=encrypted_fields.fields.EncryptedTextField(),
        ),
    ]
